{% set name = "tuspy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tuspy-{{ version }}.tar.gz
  sha256: 09a81eba7b0ce4da7870961721892c62f1d62570913bcef6727ef5599e3f4181

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi >=2018.1.18
    - future >=0.16.0
    - python >=3.6
    - requests >=2.18.4
    - six >=1.11.0
    - tinydb >=3.5.0

test:
  imports:
    - tusclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/tus/tus-py-client/
  summary: A Python client for the tus resumable upload protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsoranzo
