{% set name = "tuspy" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tuspy-{{ version }}.tar.gz
  sha256: f8c36bf8cd3a79329a571fec9706fdc675a73619cae3bf9af80d8a245e87e36e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp >=3.6.2
    - python >=3.6
    - requests >=2.18.4
    - six >=1.11.0
    - tinydb >=3.5.0

test:
  imports:
    - tusclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tus/tus-py-client/
  summary: A Python client for the tus resumable upload protocol
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsoranzo
